### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by generer** [Alecaddd/awps-cli#1]
I hit a problem, can you help?

C:\workspace\websites\wpawps\wp-content\themes>awps new sunny

Summoning application..
Downloading Package..

  [GuzzleHttp\Exception\RequestException]
  cURL error 60: SSL certificate problem: unable to get local issuer certific
  ate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

new <name>

**Comment by generer** [comment]
worng place to post.

**Comment by esmaei1** [comment]
I had the same problem.
