### ISSUE TITLE
Linux subsystem on windows

### ISSUE THREAD

**Issue by a-zhary** [Alecaddd/awps-cli#13]
Hey Alex,
I installed WSL for Windows and zsh
my zsh config look like this for composer
export PATH=$HOME/bin:/usr/local/bin:$HOME/.config/composer/vendor/bin:$PATH
I installed awps-cli, but "zsh: command not found: awps"

composer --version
Composer version 1.9.0 2019-08-02 20:55:32

which composer
/usr/local/bin/composer

What I'm doing wrong?

**Comment by cjperko** [comment]
When you installed awps-cli with composer, where did it install to?  On my WSL it installed to:

**/home/cperko/.composer/vendor/bin/awps**

So in my case, I updated my PATH variable to include **/home/cperko/.composer/vendor/bin** and it works.

If you re-install it, watch the console.  It should say something like *Changed current directory to ...* and show the directory.

**Comment by a-zhary** [comment]
Thanks, i add new path in zshconfig
`export PATH=/home/anton/.composer/vendor/bin:$HOME/bin:/usr/local/bin:$HOME/.config/composer/vendor/bin:$PATH`
It works!
