### ISSUE TITLE
awps: command not found

### ISSUE THREAD

**Issue by SamThilmany** [Alecaddd/awps-cli#2]
Hey Alex,

I installed the `awps-cli` as supposed with `composer global require "alecaddd/awps-cli"` but when trying to generate a new theme folder with `awps new theme_name` I get the message, that `awps` is not found. I entered the `.composer` directory and checked if the code was downloaded correctly and it seems to be! There is a folder named `alecaddd` containing the `awps-cli`.

What could be the problem here?

___

I'm running on macOS Sierra Version 10.12.4.
I've got the latest version of Composer (1.4.2).

**Comment by Alecaddd** [comment]
@SamThilmany Are you able to run any other composer related package, globally?
Do you have the PATH variable properly setup in your .bashrc?
This is mine
`export PATH=$HOME/bin:/usr/local/bin:~/.composer/vendor/bin:$PATH`

**Comment by JacquesvanWyk** [comment]
Hi Alex
i get the same problem and i have composer installed just did composer version and i definitely have composer installed.I am on windows i have checked the composer bin and it is there but command dont seem to work.I dont know much about composer.

If i run it in that folder it works so i guess its not global.How do i make this global?

**Comment by Alecaddd** [comment]
@JacquesvanWyk is you composer globally executable from any directory?
Did you check if a symlink to the awps file is inside this folder `~/.composer/vendor/bin`
Can you show me your .bashrc file?

**Comment by SamThilmany** [comment]
My `.bashrc` is completely empty. What does this path do? How can I find out, how it should look in my case and save it inside the `.bashrc`?

PS: I never used composer, so I have no idea, if any other package works. All I know is that the `npm` packages work fine.

**Comment by Alecaddd** [comment]
@SamThilmany No problem, I can explain to you what to do, `composer` can be a little tricky at the beginning.

First, are you using the default terminal of MacOS?
If so you're running the default shell.
You can tell your terminal to use some specific paths or "look" in specific directories when you execute a program, thanks to the .bashrc file in your home directory.

Edit your the file in this location `~/.bashrc` and add this line to the file
`export PATH=$HOME/bin:/usr/local/bin:~/.composer/vendor/bin:$PATH`

With this `export`, you're including the `bin` and `composer` folder in your global PATH variable, so whenever you run a package that you installed globally, your terminal will know that it has to look inside those folders to find that package.

**Comment by SamThilmany** [comment]
Thats very kind! ☺️

Yes, I'm using the default terminal. I just wrote that line to the `~/.bashrc`, but it still says: `awps: command not found`.

I don't have to replace those variables `$HOME` and `$PATH` do I?

---

I entered the file with `nano ~/.bashrc`, then pasted the line of code, saved it with `^O` and closed the code editor with `^X`. That's all right isn't it? I then restarted Terminal to make sure everything is reloaded and tested the simple `awps` command that should return the help page.

**Comment by Alecaddd** [comment]
@SamThilmany Yep, your process is correct.
Did you restart the terminal? After you update the `.bashrc` file you need to reload the terminal in order to use the new commands.

**Comment by SamThilmany** [comment]
Got it!

I did only restart the terminal, but that seems to be not enough. I now reinitialized the `.bashrc` settings by executing the `. ~/.bashrc` command. And now it works just fine.

Thank you very much for your help! You're great! 👍

**Comment by Alecaddd** [comment]
@SamThilmany Oh sweet, I'm glad it worked.
Next time you need to edit the bashrc file you can also try typing `source ~/.bashrc`, and that should reload the settings without forcing you to restart the terminal.

@JacquesvanWyk did you solve your problem? Can I close this issue?

**Comment by JacquesvanWyk** [comment]
@Alecaddd this is the files in vendor but where do i find the .bashc file?
![alex](https://cloud.githubusercontent.com/assets/12008702/26217503/ef946f80-3c07-11e7-85e8-bd14e5c0909d.PNG)

**Comment by Alecaddd** [comment]
@JacquesvanWyk ok, because you're on Windows, the PATH is managed in a slightly different way.

Open your command line with Administrator privileges, and then execute this command:
`setx /M path "%path%;%appdata%\Composer\vendor\bin"`

Of if this command doesn't work, try this:
`set PATH=%PATH%;%USERPROFILE%\AppData\Roaming\Composer\vendor\bi‌​n`

This should update your PATH variable and let you use Composer packages globally from anywhere.

**Comment by JacquesvanWyk** [comment]
Thanks i use cmder and now learned to change the user-profile file and set paths there.I used set "PATH=%appdata%\Composer\vendor\bin;%PATH%" and then had message that php was not recognised and then just had to set path to php aswell.So i am all set.Thanks again

**Comment by Alecaddd** [comment]
Wonderful news!

Closing this issue.
