### ISSUE TITLE
Issue with AwpsJetpack class when using a non-default namespace

### ISSUE THREAD

**Issue by BaronVonPerko** [Alecaddd/awps-cli#5]
When using the CLI, if you give it a new namespace (different than the default 'Awps'), the theme will have an error when trying to load the AwpsJetpack class.  

The CLI renames all instances of Awps.  For instance, given a new namespace of 'test', the Init.php file will now try to load something at Plugins\testJetpack.php.  However, the file is called AwpsJetpack.php, and the class within it is called testJetpack.

A simple work around for now is to rename the AwpsJetpack.php file to testJetpack.php.

**Comment by Alecaddd** [comment]
That's your fault 😝 
I'm currently rebuilding the CLI to accommodate the scaffolding features to init the team with a different configuration. I will take a look at the namespace update process and fix the issue.
Cheers

**Comment by BaronVonPerko** [comment]
Hahaha yeah :P  Let me know if you need any help!

**Comment by Alecaddd** [comment]
Fixed in the latest release of AWPS by renaming the default file `ThemeJetpack.php`
